#!/bin/bash

source ~/.config/bash_colors.sh

if [ $# -eq 0 ]
then
  COMMIT_MSG="update"
else
  COMMIT_MSG="$@"
fi

printf "${BLUE}Pull changes from remote...\n${COLOR_NC}"
git pull

printf "${BLUE}Commit...\n${COLOR_NC}"
git add .
git commit -m "$COMMIT_MSG"

printf "${BLUE}Push to remote...\n${COLOR_NC}"
git push --follow-tags
