#!/usr/bin/env bash

# Colors

#COLOR='\033[0;KEYm'
red='\033[0;91m'
blue='\033[0;34m'
green='\033[0;92m'
bold='\033[1m'
nc='\033[0m' # No Color

run() {
	if ! $@; then
		printf "${red}Command \`$@\` returned error${nc}!\n"
		exit 1
	fi
}

if [ "$EUID" -ne 0 ];then 
	printf "${red}Please run as root${nc}!\n"
	exit 1
fi

printf "${blue}Update database...${nc}\n"

run pacman -Sy

printf "\n${green}Installing code (vs code)...${nc}\n"

run pacman -S code --noconfirm

printf "\n${green}Installing intellij-idea-community-edition...${nc}\n"

run pacman -S intellij-idea-community-edition --noconfirm

printf "\n\n${bold}Done${nc}!\n"

